
[versions]
compose-plugin = "1.8.2"
agp = "8.11.1"
kotlin = "2.1.0"
kotlin-ksp = "2.1.0-1.0.29"
kotlin-coroutine = "1.10.2"
concurrentFutures = "1.3.0"
compose = "1.8.3"
compose-activity = "1.10.1"
shimmer = "1.3.3"
coil = "2.7.0"
coil3 = "3.3.0"
room = "2.7.2"
sqlite = "2.5.2"
media3 = "1.8.0"
ktor = "3.2.3"
brotli = "0.1.2"
palette = "1.0.0"
desugaring = "2.1.5"
appcompat = "1.7.1"
support = "1.0.0"
media = "1.7.1"
material = "1.9.2"
materialdesktop = "1.7.3"
material3 = "1.4.0"
androidmaterial = "1.13.0"
constraintlayout = "1.1.1"
translator = "1.1.1"
kotlin-csv = "1.10.0"
monetcompat = "0.4.1"
navigation = "2.9.5"
timber = "5.0.1"
crypto = "1.1.0"
loggingInterceptor = "5.1.0"
math3 = "3.6.1"
toasty = "1.5.2"
haze = "0.7.3"
androidyoutubeplayer = "13.0.0"
androidyoutubeplayercast = "0.32"
mediarouter = "1.8.1"
glance = "1.1.1"
kizzyrpc = "1.0.71"
gson = "2.13.2"
mediaPlayerKMP = "2.1.0"
navigationKMP = "2.9.0"
vlcj = "4.11.0"
kotlinxCoroutinesSwing = "1.10.2"
hilt = "2.57.2"
hypnoticcanvas = "0.4.1"
okhttpDnsOverHttps = "5.1.0"
reorderable = "3.0.0"
multidex = "2.0.1"
fastscroller = "0.3.2"
workmanager = "2.10.5"
accompanist = "0.37.3"


[libraries]
kotlin-coroutines = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-coroutine"}
kotlin-coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "kotlin-coroutine" }
kotlin-concurrent-futures = { group = "androidx.concurrent", name = "concurrent-futures-ktx", version.ref = "concurrentFutures" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose-ui = {group = "androidx.compose.ui", name = "ui", version.ref = "compose"}
compose-ui-util = {group = "androidx.compose.ui", name = "ui-util", version.ref = "compose"}
compose-ui-graphics-android = {group = "androidx.compose.ui", name = "ui-graphics-android", version.ref = "compose"}
compose-ripple = {group = "androidx.compose.material", name = "material-ripple", version.ref = "compose"}
compose-shimmer = {group = "com.valentinilk.shimmer", name = "compose-shimmer", version.ref = "shimmer"}
compose-activity = {group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity"}
compose-animation = {group = "androidx.compose.animation", name = "animation", version.ref = "compose"}
compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "compose"}
compose-coil = {group = "io.coil-kt", name = "coil-compose", version.ref = "coil"}
room = {group = "androidx.room", name = "room-ktx", version.ref = "room"}
room-compiler = {group = "androidx.room", name = "room-compiler", version.ref = "room"}
room-runtime = {group = "androidx.room", name = "room-runtime", version.ref = "room"}
room-sqlite-bundled = { module= "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
media3-exoplayer = {group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3"}
media3-session = {group = "androidx.media3", name = "media3-session", version.ref = "media3"}
media3-datasource-okhttp = {group = "androidx.media3", name = "media3-datasource-okhttp", version.ref = "media3"}
media3-ui = {group = "androidx.media3", name = "media3-ui", version.ref = "media3"}
ktor-client-core = {group = "io.ktor", name = "ktor-client-core", version.ref = "ktor"}
ktor-client-okhttp = {group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor"}
ktor-client-content-negotiation = {group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor"}
ktor-client-encoding = {group = "io.ktor", name = "ktor-client-encoding", version.ref = "ktor"}
ktor-client-serialization = {group = "io.ktor", name = "ktor-client-serialization", version.ref = "ktor"}
ktor-serialization-json = {group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor"}
ktor-serialization-kotlinx-xml = { group = "io.ktor", name = "ktor-serialization-kotlinx-xml", version.ref = "ktor" }
ktor-serialization-kotlinx-protobuf = { group = "io.ktor", name = "ktor-serialization-kotlinx-protobuf", version.ref = "ktor" }
brotli = {group = "org.brotli", name = "dec", version.ref = "brotli"}
palette = {group = "androidx.palette", name = "palette", version.ref = "palette"}
desugaring = {group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugaring"}
desugaring-nio = {group = "com.android.tools", name = "desugar_jdk_libs_nio", version.ref = "desugaring"}
appcompat = {group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat"}
appcompat-resources = {group = "androidx.appcompat", name = "appcompat-resources", version.ref = "appcompat"}
support = {group = "androidx.legacy", name = "legacy-support-v4", version.ref = "support"}
media = {group = "androidx.media", name = "media", version.ref = "media"}
material = {group = "androidx.compose.material", name = "material", version.ref = "material"}
material-icon-desktop = {group = "org.jetbrains.compose.material", name = "material-icons-extended-desktop", version.ref = "materialdesktop"}
material3 = {group = "androidx.compose.material3", name = "material3-android", version.ref = "material3"}
androidmaterial = {group = "com.google.android.material", name = "material", version.ref = "androidmaterial"}
constraintlayout = {group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout"}
translator = { group = "com.github.therealbush", name = "translator", version.ref = "translator"}
kotlin-csv = { group = "com.github.doyaaaaaken", name = "kotlin-csv-jvm", version.ref = "kotlin-csv"}
monetcompat = { group = "com.github.KieronQuinn", name = "MonetCompat", version.ref = "monetcompat"}
navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation"}
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber"}
crypto = { group = "androidx.security", name = "security-crypto", version.ref = "crypto"}
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
math3 = {group = "org.apache.commons", name = "commons-math3", version.ref = "math3"}
toasty = {group = "com.github.GrenderG", name = "Toasty", version.ref = "toasty"}
haze = {group = "dev.chrisbanes.haze", name = "haze", version.ref = "haze"}
androidyoutubeplayer = {group = "com.pierfrancescosoffritti.androidyoutubeplayer", name = "core", version.ref = "androidyoutubeplayer"}
androidyoutubeplayer-custom-ui = {group = "com.pierfrancescosoffritti.androidyoutubeplayer", name = "custom-ui", version.ref = "androidyoutubeplayer"}
androidyoutubeplayer-chromecast-sender = {group = "com.pierfrancescosoffritti.androidyoutubeplayer", name = "chromecast-sender", version.ref = "androidyoutubeplayercast"}
androidx-mediarouter = { group = "androidx.mediarouter", name = "mediarouter", version.ref = "mediarouter" }
glance-widgets = {group = "androidx.glance", name = "glance-appwidget", version.ref = "glance"}
kizzy-rpc = {group = "com.github.dead8309", name = "KizzyRPC", version.ref = "kizzyrpc"}
gson = {group = "com.google.code.gson", name = "gson", version.ref = "gson"}
mediaplayer-kmp = { group = "io.github.khubaibkhan4", name = "mediaplayer-kmp", version.ref = "mediaPlayerKMP" }
navigation-kmp = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigationKMP"}
vlcj = { group = "uk.co.caprica", name = "vlcj", version.ref = "vlcj"}
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil-compose-core = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil3" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil3" }
coil-mp = { module = "io.coil-kt.coil3:coil", version.ref = "coil3" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCoroutinesSwing" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hypnoticcanvas = {group = "com.mikepenz.hypnoticcanvas", name = "hypnoticcanvas", version.ref = "hypnoticcanvas"}
hypnoticcanvas-shaders = {group = "com.mikepenz.hypnoticcanvas", name = "hypnoticcanvas-shaders", version.ref = "hypnoticcanvas"}

androidx-webkit = { group = "androidx.webkit", name = "webkit", version = "1.14.0" }
okhttp-dnsoverhttps = { group = "com.squareup.okhttp3", name = "okhttp-dnsoverhttps", version.ref = "okhttpDnsOverHttps" }
room-backup = { group = "de.raphaelebner", name = "roomdatabasebackup", version = "1.1.0" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
fastscroller = { group = "io.github.oikvpqya.compose.fastscroller", name = "fastscroller-core", version.ref = "fastscroller" }
fastscroller-material3 = { group = "io.github.oikvpqya.compose.fastscroller", name = "fastscroller-material3", version.ref = "fastscroller" }
fastscroller-indicator = { group = "io.github.oikvpqya.compose.fastscroller", name = "fastscroller-indicator", version.ref = "fastscroller" }
workmanager = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workmanager" }

accompanist = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
room = { id = "androidx.room", version.ref = "room" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }


